TEMPLATE = app
TARGET = GomokuHalSoft

QT += qml quick
QT += multimedia
CONFIG += c++11
CONFIG += static

SOURCES += \
    ../../GomokuGame_SRC/Sources/DataContainers/Graph.cpp \
    ../../GomokuGame_SRC/Sources/DataContainers/GraphIterator.cpp \
    ../../GomokuGame_SRC/Sources/DataContainers/VectorLight.cpp \
    ../../GomokuGame_SRC/Sources/DataContainers/VectorLightIterator.cpp \
    ../../GomokuGame_SRC/Sources/SearchAlgorithms/AlphaBeta.cpp \
    ../../GomokuGame_SRC/Sources/SearchAlgorithms/MinMax.cpp \
    ../../GomokuGame_SRC/Sources/SearchAlgorithms/StateEvaluation.cpp \
    ../../GomokuGame_SRC/Sources/Threats/Threat2CaseA.cpp \
    ../../GomokuGame_SRC/Sources/Threats/Threat2CaseAA.cpp \
    ../../GomokuGame_SRC/Sources/Threats/Threat2CaseB.cpp \
    ../../GomokuGame_SRC/Sources/Threats/Threat2CaseC.cpp \
    ../../GomokuGame_SRC/Sources/Threats/Threat3CaseA.cpp \
    ../../GomokuGame_SRC/Sources/Threats/Threat3CaseAA.cpp \
    ../../GomokuGame_SRC/Sources/Threats/Threat3CaseB.cpp \
    ../../GomokuGame_SRC/Sources/Threats/Threat3CaseC.cpp \
    ../../GomokuGame_SRC/Sources/Threats/Threat4CaseA.cpp \
    ../../GomokuGame_SRC/Sources/Threats/Threat4CaseAA.cpp \
    ../../GomokuGame_SRC/Sources/Threats/Threat4CaseB.cpp \
    ../../GomokuGame_SRC/Sources/Threats/Threat4CaseC.cpp \
    ../../GomokuGame_SRC/Sources/Threats/ThreatFinder.cpp \
    ../../GomokuGame_SRC/Sources/Threats/ThreatsBloodRelation.cpp \
    ../../GomokuGame_SRC/Sources/Threats/ThreatWinner.cpp \
    ../../GomokuGame_SRC/Sources/BoardIterator.cpp \
    ../../GomokuGame_SRC/Sources/BoardScore.cpp \
    ../../GomokuGame_SRC/Sources/GomokuBoard.cpp \
    ../../GomokuGame_SRC/Sources/GomokuGame.cpp \
    ../../GomokuGame_SRC/Sources/OpenBook.cpp \
    ../../GomokuGame_SRC/Sources/Score.cpp \
    ../../GomokuGame_SRC/Sources/Spotter.cpp \
    ../../GomokuGame_SRC/Sources/Logger.cpp \
    main.cpp \
    GomokuBackEnd.cpp \
    GomokuInputStream.cpp \
    GomokuOutputStream.cpp

RESOURCES += qml.qrc \
            Sound\newGame.wav \
            Sound\youWon.wav \
            Sound\yourMove.wav \
            Sound\youLost.wav \
            Sound\pcMove.wav \
            Images\mainBackGroundBlack.jpg \
            Images\black50.gif \
            Images\white50.gif \
            Images\red50.gif \
            Images\black50Redmark.gif \
            Images\white50RedMark.gif \
            Images/markedFields/excited.gif\
            Images/menu/icons8-time-machine-filled-100.png\
            Images/menu/icons8-time-machine-100.png\
            Images/menu/icons8-info-filled-100.png\
            Images/menu/icons8-info-100.png\
            Images/menu/icons8-help-filled-100.png\
            Images/menu/icons8-help-100.png\
            Images/menu/icons8-go-back-filled-100.png\
            Images/menu/icons8-go-back-100.png\
            Images/menu/icons8-cancel-filled-100.png\
            Images/menu/icons8-cancel-100.png\
            Images/menu/icons8-time-machine-filled-100_disabled.png\
            Images/menu/icons8-go-back-filled-100_disabled.png\
            Images/menu/icons8-cancel-filled-100_disabled.png\
            Images/boardBorder/border_bottom_01.gif \
            Images/boardBorder/border_bottom_02.gif \
            Images/boardBorder/border_bottom_03.gif \
            Images/boardBorder/border_bottom_04.gif \
            Images/boardBorder/border_bottom_05.gif \
            Images/boardBorder/border_bottom_06.gif \
            Images/boardBorder/border_bottom_07.gif \
            Images/boardBorder/border_bottom_08.gif \
            Images/boardBorder/border_bottom_09.gif \
            Images/boardBorder/border_bottom_10.gif \
            Images/boardBorder/border_bottom_11.gif \
            Images/boardBorder/border_bottom_12.gif \
            Images/boardBorder/border_bottom_13.gif \
            Images/boardBorder/border_bottom_14.gif \
            Images/boardBorder/border_bottom_15.gif \
            Images/boardBorder/border_bottom_16.gif \
            Images/boardBorder/border_bottom_17.gif \
            Images/boardBorder/border_bottom_18.gif \
            Images/boardBorder/border_bottom_19.gif \
            Images/boardBorder/border_left_01.gif \
            Images/boardBorder/border_left_02.gif \
            Images/boardBorder/border_left_03.gif \
            Images/boardBorder/border_left_04.gif \
            Images/boardBorder/border_left_05.gif \
            Images/boardBorder/border_left_06.gif \
            Images/boardBorder/border_left_07.gif \
            Images/boardBorder/border_left_08.gif \
            Images/boardBorder/border_left_09.gif \
            Images/boardBorder/border_left_10.gif \
            Images/boardBorder/border_left_11.gif \
            Images/boardBorder/border_left_12.gif \
            Images/boardBorder/border_left_13.gif \
            Images/boardBorder/border_left_14.gif \
            Images/boardBorder/border_left_15.gif \
            Images/boardBorder/border_left_16.gif \
            Images/boardBorder/border_left_17.gif \
            Images/boardBorder/border_left_18.gif \
            Images/boardBorder/border_left_19.gif \
            Images/boardBorder/border_right_01.gif \
            Images/boardBorder/border_right_02.gif \
            Images/boardBorder/border_right_03.gif \
            Images/boardBorder/border_right_04.gif \
            Images/boardBorder/border_right_05.gif \
            Images/boardBorder/border_right_06.gif \
            Images/boardBorder/border_right_07.gif \
            Images/boardBorder/border_right_08.gif \
            Images/boardBorder/border_right_09.gif \
            Images/boardBorder/border_right_10.gif \
            Images/boardBorder/border_right_11.gif \
            Images/boardBorder/border_right_12.gif \
            Images/boardBorder/border_right_13.gif \
            Images/boardBorder/border_right_14.gif \
            Images/boardBorder/border_right_15.gif \
            Images/boardBorder/border_right_16.gif \
            Images/boardBorder/border_right_17.gif \
            Images/boardBorder/border_right_18.gif \
            Images/boardBorder/border_right_19.gif \
            Images/boardBorder/border_top_01.gif \
            Images/boardBorder/border_top_02.gif \
            Images/boardBorder/border_top_03.gif \
            Images/boardBorder/border_top_04.gif \
            Images/boardBorder/border_top_05.gif \
            Images/boardBorder/border_top_06.gif \
            Images/boardBorder/border_top_07.gif \
            Images/boardBorder/border_top_08.gif \
            Images/boardBorder/border_top_09.gif \
            Images/boardBorder/border_top_10.gif \
            Images/boardBorder/border_top_11.gif \
            Images/boardBorder/border_top_12.gif \
            Images/boardBorder/border_top_13.gif \
            Images/boardBorder/border_top_14.gif \
            Images/boardBorder/border_top_15.gif \
            Images/boardBorder/border_top_16.gif \
            Images/boardBorder/border_top_17.gif \
            Images/boardBorder/border_top_18.gif \
            Images/boardBorder/border_top_19.gif \
            Images/boardBorder/corner_bottom_left.gif \
            Images/boardBorder/corner_bottom_right.gif \
            Images/boardBorder/corner_top_left.gif \
            Images/boardBorder/corner_top_right.gif\
            Images/boardInterior/interior_01.gif \
            Images/boardInterior/interior_02.gif \
            Images/boardInterior/interior_03.gif \
            Images/boardInterior/interior_04.gif \
            Images/boardInterior/interior_05.gif \
            Images/boardInterior/interior_06.gif \
            Images/boardInterior/interior_07.gif \
            Images/boardInterior/interior_08.gif \
            Images/boardInterior/interior_09.gif \
            Images/boardInterior/interior_10.gif \
            Images/boardInterior/interior_11.gif \
            Images/boardInterior/interior_12.gif \
            Images/boardInterior/interior_13.gif \
            Images/boardInterior/interior_14.gif \
            Images/boardInterior/interior_15.gif \
            Images/boardInterior/interior_16.gif \
            Images/boardInterior/interior_17.gif \
            Images/boardInterior/interior_18.gif \
            Images/boardInterior/interior_19.gif \
            Images/boardInterior/interior_20.gif \
            Images/boardInterior/interior_21.gif \
            Images/boardInterior/interior_22.gif \
            Images/boardInterior/interior_23.gif \
            Images/boardInterior/interior_24.gif \
            Images/boardInterior/interior_25.gif \
            Images/boardInterior/interior_26.gif \
            Images/boardInterior/interior_27.gif \
            Images/boardInterior/interior_28.gif \
            Images/boardInterior/interior_29.gif \
            Images/boardInterior/interior_30.gif \
            Images/boardInterior/interior_31.gif \
            Images/boardInterior/interior_32.gif \
            Images/boardInterior/interior_33.gif \
            Images/boardInterior/interior_34.gif \
            Images/boardInterior/interior_35.gif \
            Images/boardInterior/interior_36.gif \
            Images/boardInterior/interior_37.gif \
            Images/boardInterior/interior_38.gif \
            Images/boardInterior/interior_39.gif \
            Images/boardInterior/interior_40.gif \
            Images/boardInterior/interior_41.gif \
            Images/boardInterior/interior_42.gif \
            Images/boardInterior/interior_43.gif \
            Images/boardInterior/interior_44.gif \
            Images/boardInterior/interior_45.gif \
            Images/boardInterior/interior_46.gif \
            Images/boardInterior/interior_47.gif \
            Images/boardInterior/interior_48.gif \
            Images/boardInterior/interior_49.gif \
            Images/boardInterior/interior_50.gif \
            Images/boardInterior/interior_51.gif \
            Images/boardInterior/interior_52.gif \
            Images/boardInterior/interior_53.gif \
            Images/boardInterior/interior_54.gif \
            Images/boardInterior/interior_55.gif \
            Images/boardInterior/interior_56.gif \
            Images/boardInterior/interior_57.gif \
            Images/boardInterior/interior_58.gif \
            Images/boardInterior/interior_59.gif \
            Images/boardInterior/interior_60.gif \
            Images/boardInterior/interior_61.gif \
            Images/boardInterior/interior_62.gif \
            Images/boardInterior/interior_63.gif \
            Images/boardInterior/interior_64.gif \
            Images/boardInterior/interior_65.gif \
            Images/boardInterior/interior_66.gif \
            Images/boardInterior/interior_67.gif \
            Images/boardInterior/interior_68.gif \
            Images/boardInterior/interior_69.gif \
            Images/boardInterior/interior_70.gif \
            Images/boardInterior/interior_71.gif \
            Images/boardInterior/interior_72.gif \
            Images/boardInterior/interior_73.gif \
            Images/boardInterior/interior_74.gif \
            Images/boardInterior/interior_75.gif \
            Images/boardInterior/interior_76.gif \
            Images/boardInterior/interior_77.gif \
            Images/boardInterior/interior_78.gif \
            Images/boardInterior/interior_79.gif \
            Images/boardInterior/interior_80.gif \
            Images/boardInterior/interior_81.gif \
            Images/boardInterior/interior_82.gif \
            Images/boardInterior/interior_83.gif \
            Images/boardInterior/interior_84.gif \
            Images/boardInterior/interior_85.gif \
            Images/boardInterior/interior_86.gif \
            Images/boardInterior/interior_87.gif \
            Images/boardInterior/interior_88.gif \
            Images/boardInterior/interior_89.gif \
            Images/boardInterior/interior_90.gif \
            Images/boardInterior/interior_91.gif \
            Images/boardInterior/interior_92.gif \
            Images/boardInterior/interior_93.gif \
            Images/boardInterior/interior_94.gif \
            Images/boardInterior/interior_95.gif \
            Images/boardInterior/interior_96.gif \
            Images/boardInterior/interior_97.gif \
            Images/boardInterior/interior_98.gif \
            Images/boardInterior/interior_99.gif \
            Images/boardInterior/interior_100.gif \
            Images/boardInterior/interior_101.gif \
            Images/boardInterior/interior_102.gif \
            Images/boardInterior/interior_103.gif \
            Images/boardInterior/interior_104.gif \
            Images/boardInterior/interior_105.gif \
            Images/boardInterior/interior_106.gif \
            Images/boardInterior/interior_107.gif \
            Images/boardInterior/interior_108.gif \
            Images/boardInterior/interior_109.gif \
            Images/boardInterior/interior_110.gif \
            Images/boardInterior/interior_111.gif \
            Images/boardInterior/interior_112.gif \
            Images/boardInterior/interior_113.gif \
            Images/boardInterior/interior_114.gif \
            Images/boardInterior/interior_115.gif \
            Images/boardInterior/interior_116.gif \
            Images/boardInterior/interior_117.gif \
            Images/boardInterior/interior_118.gif \
            Images/boardInterior/interior_119.gif \
            Images/boardInterior/interior_120.gif \
            Images/boardInterior/interior_121.gif \
            Images/boardInterior/interior_122.gif \
            Images/boardInterior/interior_123.gif \
            Images/boardInterior/interior_124.gif \
            Images/boardInterior/interior_125.gif \
            Images/boardInterior/interior_126.gif \
            Images/boardInterior/interior_127.gif \
            Images/boardInterior/interior_128.gif \
            Images/boardInterior/interior_129.gif \
            Images/boardInterior/interior_130.gif \
            Images/boardInterior/interior_131.gif \
            Images/boardInterior/interior_132.gif \
            Images/boardInterior/interior_133.gif \
            Images/boardInterior/interior_134.gif \
            Images/boardInterior/interior_135.gif \
            Images/boardInterior/interior_136.gif \
            Images/boardInterior/interior_137.gif \
            Images/boardInterior/interior_138.gif \
            Images/boardInterior/interior_139.gif \
            Images/boardInterior/interior_140.gif \
            Images/boardInterior/interior_141.gif \
            Images/boardInterior/interior_142.gif \
            Images/boardInterior/interior_143.gif \
            Images/boardInterior/interior_144.gif \
            Images/boardInterior/interior_145.gif \
            Images/boardInterior/interior_146.gif \
            Images/boardInterior/interior_147.gif \
            Images/boardInterior/interior_148.gif \
            Images/boardInterior/interior_149.gif \
            Images/boardInterior/interior_150.gif \
            Images/boardInterior/interior_151.gif \
            Images/boardInterior/interior_152.gif \
            Images/boardInterior/interior_153.gif \
            Images/boardInterior/interior_154.gif \
            Images/boardInterior/interior_155.gif \
            Images/boardInterior/interior_156.gif \
            Images/boardInterior/interior_157.gif \
            Images/boardInterior/interior_158.gif \
            Images/boardInterior/interior_159.gif \
            Images/boardInterior/interior_160.gif \
            Images/boardInterior/interior_161.gif \
            Images/boardInterior/interior_162.gif \
            Images/boardInterior/interior_163.gif \
            Images/boardInterior/interior_164.gif \
            Images/boardInterior/interior_165.gif \
            Images/boardInterior/interior_166.gif \
            Images/boardInterior/interior_167.gif \
            Images/boardInterior/interior_168.gif \
            Images/boardInterior/interior_169.gif \
            Images/boardInterior/interior_170.gif \
            Images/boardInterior/interior_171.gif \
            Images/boardInterior/interior_172.gif \
            Images/boardInterior/interior_173.gif \
            Images/boardInterior/interior_174.gif \
            Images/boardInterior/interior_175.gif \
            Images/boardInterior/interior_176.gif \
            Images/boardInterior/interior_177.gif \
            Images/boardInterior/interior_178.gif \
            Images/boardInterior/interior_179.gif \
            Images/boardInterior/interior_180.gif \
            Images/boardInterior/interior_181.gif \
            Images/boardInterior/interior_182.gif \
            Images/boardInterior/interior_183.gif \
            Images/boardInterior/interior_184.gif \
            Images/boardInterior/interior_185.gif \
            Images/boardInterior/interior_186.gif \
            Images/boardInterior/interior_187.gif \
            Images/boardInterior/interior_188.gif \
            Images/boardInterior/interior_189.gif \
            Images/boardInterior/interior_190.gif \
            Images/boardInterior/interior_191.gif \
            Images/boardInterior/interior_192.gif \
            Images/boardInterior/interior_193.gif \
            Images/boardInterior/interior_194.gif \
            Images/boardInterior/interior_195.gif \
            Images/boardInterior/interior_196.gif \
            Images/boardInterior/interior_197.gif \
            Images/boardInterior/interior_198.gif \
            Images/boardInterior/interior_199.gif \
            Images/boardInterior/interior_200.gif \
            Images/boardInterior/interior_201.gif \
            Images/boardInterior/interior_202.gif \
            Images/boardInterior/interior_203.gif \
            Images/boardInterior/interior_204.gif \
            Images/boardInterior/interior_205.gif \
            Images/boardInterior/interior_206.gif \
            Images/boardInterior/interior_207.gif \
            Images/boardInterior/interior_208.gif \
            Images/boardInterior/interior_209.gif \
            Images/boardInterior/interior_210.gif \
            Images/boardInterior/interior_211.gif \
            Images/boardInterior/interior_212.gif \
            Images/boardInterior/interior_213.gif \
            Images/boardInterior/interior_214.gif \
            Images/boardInterior/interior_215.gif \
            Images/boardInterior/interior_216.gif \
            Images/boardInterior/interior_217.gif \
            Images/boardInterior/interior_218.gif \
            Images/boardInterior/interior_219.gif \
            Images/boardInterior/interior_220.gif \
            Images/boardInterior/interior_221.gif \
            Images/boardInterior/interior_222.gif \
            Images/boardInterior/interior_223.gif \
            Images/boardInterior/interior_224.gif \
            Images/boardInterior/interior_225.gif \
            Images/boardInterior/interior_226.gif \
            Images/boardInterior/interior_227.gif \
            Images/boardInterior/interior_228.gif \
            Images/boardInterior/interior_229.gif \
            Images/boardInterior/interior_230.gif \
            Images/boardInterior/interior_231.gif \
            Images/boardInterior/interior_232.gif \
            Images/boardInterior/interior_233.gif \
            Images/boardInterior/interior_234.gif \
            Images/boardInterior/interior_235.gif \
            Images/boardInterior/interior_236.gif \
            Images/boardInterior/interior_237.gif \
            Images/boardInterior/interior_238.gif \
            Images/boardInterior/interior_239.gif \
            Images/boardInterior/interior_240.gif \
            Images/boardInterior/interior_241.gif \
            Images/boardInterior/interior_242.gif \
            Images/boardInterior/interior_243.gif \
            Images/boardInterior/interior_244.gif \
            Images/boardInterior/interior_245.gif \
            Images/boardInterior/interior_246.gif \
            Images/boardInterior/interior_247.gif \
            Images/boardInterior/interior_248.gif \
            Images/boardInterior/interior_249.gif \
            Images/boardInterior/interior_250.gif \
            Images/boardInterior/interior_251.gif \
            Images/boardInterior/interior_252.gif \
            Images/boardInterior/interior_253.gif \
            Images/boardInterior/interior_254.gif \
            Images/boardInterior/interior_255.gif \
            Images/boardInterior/interior_256.gif \
            Images/boardInterior/interior_257.gif \
            Images/boardInterior/interior_258.gif \
            Images/boardInterior/interior_259.gif \
            Images/boardInterior/interior_260.gif \
            Images/boardInterior/interior_261.gif \
            Images/boardInterior/interior_262.gif \
            Images/boardInterior/interior_263.gif \
            Images/boardInterior/interior_264.gif \
            Images/boardInterior/interior_265.gif \
            Images/boardInterior/interior_266.gif \
            Images/boardInterior/interior_267.gif \
            Images/boardInterior/interior_268.gif \
            Images/boardInterior/interior_269.gif \
            Images/boardInterior/interior_270.gif \
            Images/boardInterior/interior_271.gif \
            Images/boardInterior/interior_272.gif \
            Images/boardInterior/interior_273.gif \
            Images/boardInterior/interior_274.gif \
            Images/boardInterior/interior_275.gif \
            Images/boardInterior/interior_276.gif \
            Images/boardInterior/interior_277.gif \
            Images/boardInterior/interior_278.gif \
            Images/boardInterior/interior_279.gif \
            Images/boardInterior/interior_280.gif \
            Images/boardInterior/interior_281.gif \
            Images/boardInterior/interior_282.gif \
            Images/boardInterior/interior_283.gif \
            Images/boardInterior/interior_284.gif \
            Images/boardInterior/interior_285.gif \
            Images/boardInterior/interior_286.gif \
            Images/boardInterior/interior_287.gif \
            Images/boardInterior/interior_288.gif \
            Images/boardInterior/interior_289.gif \
            Images/boardInterior/interior_290.gif \
            Images/boardInterior/interior_291.gif \
            Images/boardInterior/interior_292.gif \
            Images/boardInterior/interior_293.gif \
            Images/boardInterior/interior_294.gif \
            Images/boardInterior/interior_295.gif \
            Images/boardInterior/interior_296.gif \
            Images/boardInterior/interior_297.gif \
            Images/boardInterior/interior_298.gif \
            Images/boardInterior/interior_299.gif \
            Images/boardInterior/interior_300.gif \
            Images/boardInterior/interior_301.gif \
            Images/boardInterior/interior_302.gif \
            Images/boardInterior/interior_303.gif \
            Images/boardInterior/interior_304.gif \
            Images/boardInterior/interior_305.gif \
            Images/boardInterior/interior_306.gif \
            Images/boardInterior/interior_307.gif \
            Images/boardInterior/interior_308.gif \
            Images/boardInterior/interior_309.gif \
            Images/boardInterior/interior_310.gif \
            Images/boardInterior/interior_311.gif \
            Images/boardInterior/interior_312.gif \
            Images/boardInterior/interior_313.gif \
            Images/boardInterior/interior_314.gif \
            Images/boardInterior/interior_315.gif \
            Images/boardInterior/interior_316.gif \
            Images/boardInterior/interior_317.gif \
            Images/boardInterior/interior_318.gif \
            Images/boardInterior/interior_319.gif \
            Images/boardInterior/interior_320.gif \
            Images/boardInterior/interior_321.gif \
            Images/boardInterior/interior_322.gif \
            Images/boardInterior/interior_323.gif \
            Images/boardInterior/interior_324.gif \
            Images/boardInterior/interior_325.gif \
            Images/boardInterior/interior_326.gif \
            Images/boardInterior/interior_327.gif \
            Images/boardInterior/interior_328.gif \
            Images/boardInterior/interior_329.gif \
            Images/boardInterior/interior_330.gif \
            Images/boardInterior/interior_331.gif \
            Images/boardInterior/interior_332.gif \
            Images/boardInterior/interior_333.gif \
            Images/boardInterior/interior_334.gif \
            Images/boardInterior/interior_335.gif \
            Images/boardInterior/interior_336.gif \
            Images/boardInterior/interior_337.gif \
            Images/boardInterior/interior_338.gif \
            Images/boardInterior/interior_339.gif \
            Images/boardInterior/interior_340.gif \
            Images/boardInterior/interior_341.gif \
            Images/boardInterior/interior_342.gif \
            Images/boardInterior/interior_343.gif \
            Images/boardInterior/interior_344.gif \
            Images/boardInterior/interior_345.gif \
            Images/boardInterior/interior_346.gif \
            Images/boardInterior/interior_347.gif \
            Images/boardInterior/interior_348.gif \
            Images/boardInterior/interior_349.gif \
            Images/boardInterior/interior_350.gif \
            Images/boardInterior/interior_351.gif \
            Images/boardInterior/interior_352.gif \
            Images/boardInterior/interior_353.gif \
            Images/boardInterior/interior_354.gif \
            Images/boardInterior/interior_355.gif \
            Images/boardInterior/interior_356.gif \
            Images/boardInterior/interior_357.gif \
            Images/boardInterior/interior_358.gif \
            Images/boardInterior/interior_359.gif \
            Images/boardInterior/interior_360.gif \
            Images/boardInterior/interior_361.gif


# Additional import path used to resolve QML modules in Qt Creator's code model
QML_IMPORT_PATH =

# Default rules for deployment.
include(deployment.pri)

HEADERS += \
    ../../GomokuGame_SRC/Headers/DataContainers/Graph.hpp \
    ../../GomokuGame_SRC/Headers/DataContainers/GraphIterator.hpp \
    ../../GomokuGame_SRC/Headers/DataContainers/IteratorIf.hpp \
    ../../GomokuGame_SRC/Headers/DataContainers/PriorityQueue.hpp \
    ../../GomokuGame_SRC/Headers/DataContainers/SingleList.hpp \
    ../../GomokuGame_SRC/Headers/DataContainers/SingleListIterator.hpp \
    ../../GomokuGame_SRC/Headers/DataContainers/VectorLight.hpp \
    ../../GomokuGame_SRC/Headers/DataContainers/VectorLightIterator.hpp \
    ../../GomokuGame_SRC/Headers/SearchAlgorithms/AlphaBeta.hpp \
    ../../GomokuGame_SRC/Headers/SearchAlgorithms/MinMax.hpp \
    ../../GomokuGame_SRC/Headers/SearchAlgorithms/SearchTreeAlgorithmIf.hpp \
    ../../GomokuGame_SRC/Headers/Threats/Threat2CaseA.hpp \
    ../../GomokuGame_SRC/Headers/Threats/Threat2CaseB.hpp \
    ../../GomokuGame_SRC/Headers/Threats/Threat2CaseC.hpp \
    ../../GomokuGame_SRC/Headers/Threats/Threat3CaseA.hpp \
    ../../GomokuGame_SRC/Headers/Threats/Threat3CaseB.hpp \
    ../../GomokuGame_SRC/Headers/Threats/Threat3CaseC.hpp \
    ../../GomokuGame_SRC/Headers/Threats/Threat4CaseA.hpp \
    ../../GomokuGame_SRC/Headers/Threats/Threat4CaseB.hpp \
    ../../GomokuGame_SRC/Headers/Threats/Threat4CaseC.hpp \
    ../../GomokuGame_SRC/Headers/Threats/ThreatFinder.hpp \
    ../../GomokuGame_SRC/Headers/Threats/ThreatsBloodRelation.hpp \
    ../../GomokuGame_SRC/Headers/Threats/ThreatWinner.hpp \
    ../../GomokuGame_SRC/Headers/Board.hpp \
    ../../GomokuGame_SRC/Headers/BoardIterator.hpp \
    ../../GomokuGame_SRC/Headers/BoardScore.hpp \
    ../../GomokuGame_SRC/Headers/GomokuBoard.hpp \
    ../../GomokuGame_SRC/Headers/GomokuGame.hpp \
    ../../GomokuGame_SRC/Headers/OpenBook.hpp \
    ../../GomokuGame_SRC/Headers/Score.hpp \
    ../../GomokuGame_SRC/Headers/Spotter.hpp \
    ../../GomokuGame_SRC/Headers/TwoPlayerGame.hpp \
    ../../GomokuGame_SRC/Sources/Logger.hpp \
    GomokuBackEnd.h \
    GomokuOutputStream.h \
    GomokuInputStream.h

INCLUDEPATH += ../../GomokuGame_SRC/Headers/DataContainers \
               ../../GomokuGame_SRC/Headers/Platform/Windows \
               ../../GomokuGame_SRC/Headers/SearchAlgorithms \
               ../../GomokuGame_SRC/Headers/Threats \
               ../../GomokuGame_SRC/Headers

DEFINES += GUI_GOMOKU_GAME

DISTFILES += \
    android/AndroidManifest.xml \
    android/gradle/wrapper/gradle-wrapper.jar \
    android/gradlew \
    android/res/values/libs.xml \
    android/build.gradle \
    android/gradle/wrapper/gradle-wrapper.properties \
    android/gradlew.bat \
    android/AndroidManifest.xml \
    android/gradle/wrapper/gradle-wrapper.jar \
    android/gradlew \
    android/res/values/libs.xml \
    android/build.gradle \
    android/gradle/wrapper/gradle-wrapper.properties \
    android/gradlew.bat \
    android/AndroidManifest.xml \
    android/gradle/wrapper/gradle-wrapper.jar \
    android/gradlew \
    android/res/values/libs.xml \
    android/build.gradle \
    android/gradle/wrapper/gradle-wrapper.properties \
    android/gradlew.bat \
    android/AndroidManifest.xml \
    android/gradle/wrapper/gradle-wrapper.jar \
    android/gradlew \
    android/res/values/libs.xml \
    android/build.gradle \
    android/gradle/wrapper/gradle-wrapper.properties \
    android/gradlew.bat

ANDROID_PACKAGE_SOURCE_DIR = $$PWD/android


