pipeline {
    agent any

    options {
       timestamps()
       timeout(time: 2, unit: 'HOURS') // Increased timeout to 2 hours
    }

    parameters {
        booleanParam(name: 'RUN_UT', defaultValue: true, description: 'Run unit tests')
    }

    environment {
        PRJ = "${env.WORKSPACE}"
        DOCKER_IMAGE = 'ginar/android_qt6_img:latest'
    }

    stages {
        stage('Pull Docker Image') {
            steps {
                script {
                    // Check if the Docker image exists locally
                    def imageExists = sh(script: "docker images -q ${env.DOCKER_IMAGE}", returnStdout: true).trim()
                    if (imageExists == "") {
                        echo "Docker image ${env.DOCKER_IMAGE} not found locally. Pulling from Docker Hub..."
                        retry(2) { //try max 2x 
                            sh(script: "docker pull ${env.DOCKER_IMAGE}", returnStdout: true, returnStatus: false).eachLine { line ->
                                echo line
                            }
                        }
                        echo "Docker image ${env.DOCKER_IMAGE} successfully pulled."
                    } else {
                        echo "Docker image ${env.DOCKER_IMAGE} already exists locally. Skipping pull."
                    }

                    //Verify Docker Image
                    def imageVerify = sh(script: "docker images -q ${env.DOCKER_IMAGE}", returnStdout: true).trim()
                    if (imageVerify == "") {
                        error "Docker image ${env.DOCKER_IMAGE} not found after pull. Aborting."
                    } else {
                        echo "Docker image ${env.DOCKER_IMAGE} is available locally."
                    }
                }
            }
        }
        
        // Add further stages here as needed
    }
}
