pipeline {

    agent any

    options {
       timestamps()
       timeout(time: 1, unit: 'HOURS')
    }

    parameters {
        booleanParam(name: 'RUN_BEHAVE_TESTS', defaultValue: true, description: 'Run behave tests')
    }

    environment {
        PRJ = "${env.WORKSPACE}"
        DOCKER_DIR = "${PRJ}/utils"
        DOCKER_LABEL_COMMON="--label=job=${BUILD_TAG} --label=project=gomoku"
    }

    stages {
        stage('docker images') {
            steps {
                dir("${DOCKER_DIR}") {
                    script{
                        env.DOCKER_BUILDER_HASH = sh(script: 'git hash-object docker_build/Dockerfile', returnStdout: true).substring(0, 8)
                        env.DOCKER_DOXYGEN_HASH = sh(script: 'git hash-object docker_doxygen/Dockerfile', returnStdout: true).substring(0, 8)
                        env.DOCKER_BUILDER_TAG_ID_IMG = 'builder_img'+ ":" + env.DOCKER_BUILDER_HASH
                        env.DOCKER_DOXYGEN_TAG_ID_IMG = 'doxygen_img'+ ":" + env.DOCKER_DOXYGEN_HASH
                    }
                    sh 'cd docker_build && docker build ${DOCKER_LABEL_COMMON} --tag=${DOCKER_BUILDER_TAG_ID_IMG} .'
                    sh 'cd docker_doxygen && docker build ${DOCKER_LABEL_COMMON} --tag=${DOCKER_DOXYGEN_TAG_ID_IMG} .'
                }
            }
        }

        stage('Build') {
            parallel {
                stage('doxygen doc') {
                    steps {
                        sh 'echo "dupa1"'
                        sh 'echo ${PRJ}'
                        //sh 'ls -las'
                        sh 'echo "dupa2"'
                        // sh 'docker run  ${DOCKER_LABEL_COMMON} --label task=doxygen --rm --volume ${PRJ}:/gomoku_prj ${DOCKER_DOXYGEN_TAG_ID_IMG}'
                        // sh 'rm -f ${PRJ}/Doxygen/*.map ${PRJ}/Doxygen/*.md5 doxygen_html_doc.zip'
                        // zip zipFile: "doxygen_html_doc.zip", archive: true, dir: "${PRJ}/Doxygen"
                        // publishHTML (target : [allowMissing: true,
                        //    alwaysLinkToLastBuild: true,
                        //    keepAll: true,
                        //    reportDir: "${PRJ}/Doxygen",
                        //    reportFiles: 'index.html',
                        //    reportName: 'Code Documentation',
                        //    reportTitles: 'Doxygen documentation for gomoku project'])
                    }
                }

                // stage('build src debug') {
                //     steps {
                //         sh 'docker run ${DOCKER_LABEL_COMMON} --label task=build_debug --rm --volume ${PRJ}:/gomoku_prj -w=/gomoku_prj ${DOCKER_BUILDER_TAG_ID_IMG} mkdir build_stand_alone'
                //         sh 'docker run -e DEFAULT_TOOLCHAIN_PATH=/usr/bin ${DOCKER_LABEL_COMMON} --label task=build_debug --rm --volume ${PRJ}:/gomoku_prj -w=/gomoku_prj/build_stand_alone ${DOCKER_BUILDER_TAG_ID_IMG} cmake .. -DCMAKE_BUILD_TYPE=Debug -G"Eclipse CDT4 - Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE="../cmake/toolchain-gcc-default.cmake" -DCMAKE_EXPORT_COMPILE_COMMANDS=ON'
                //         sh 'docker run -e DEFAULT_TOOLCHAIN_PATH=/usr/bin ${DOCKER_LABEL_COMMON} --label task=build_debug --rm --volume ${PRJ}:/gomoku_prj -w=/gomoku_prj/build_stand_alone ${DOCKER_BUILDER_TAG_ID_IMG} make'
                //     }
                // }
            }
        }
        // stage('Test') {
        //     steps {
        //         echo 'Testing..'
        //     }
        // }
        // stage('Deploy') {
        //     steps {
        //         echo 'Deploying....'
        //     }
        // }
    }
}

