pipeline {

    agent any

    options {
       timestamps()
       timeout(time: 1, unit: 'HOURS')
    }

    parameters {
        booleanParam(name: 'RUN_UT_TESTS', defaultValue: true, description: 'Run unit tests')
        booleanParam(name: 'RUN_BEHAVE_TESTS', defaultValue: true, description: 'Run behave tests')
    }

    environment{
        PRJ = "${env.WORKSPACE}"
        DOCKER_DIR = "${PRJ}/utils"
        DOCKER_LAB="--label=job=${BUILD_TAG} --label=project=gomoku"
    }


    stages {
        stage('docker images'){
            steps{
                dir("${DOCKER_DIR}") {
                    script{
                        env.DOCKER_BUILDER_TAG_ID = sh(script: 'git hash-object docker_build/Dockerfile', returnStdout: true).substring(0, 8)
                        env.DOCKER_DOXYGEN_TAG_ID = sh(script: 'git hash-object docker_doxygen/Dockerfile', returnStdout: true).substring(0, 8)
                    }
                    sh 'cd docker_build && docker build ${DOCKER_LAB} --tag="gomoku_src_img" .'
                    sh 'cd docker_doxygen && docker build ${DOCKER_LAB}  --tag="gomoku_doxy_img" .'
                }
            }
        }


        stage('Build') {
            steps {
                echo 'Building..'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}

